TogetherAnne/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_scope :user do
    #get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #end
  
	
  #devise_for :users, :controllers => { :callbacks_controller_controller => "controllers/callbacks_controller_controller" }

  root 'static_pages#home'

  get 'static_pages/suggerimenti'

  get 'static_pages/aboutus'
  
  resources :users do
  	resources :monitoraggios
	resources :associaziones
	#get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
	#delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end
  

  #devise_scope :user do
    #get ' /users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    #get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  #end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TogetherAnne/app/models/monitoraggio.rb
class Monitoraggio < ApplicationRecord
   belongs_to :user, :foreign_key => 'user_id'
   validates :user_id, presence: true
   validates :frase, presence: true
   validates :citta, presence: true
   validates :regione, presence: true
   validates :giorno, presence: true
   validates :mese, presence: true
   validates :anno, presence: true
   def somma_punteggio
	    time= Time.now
	    inverno = ['January', 'February', 'December']
	    autunno = ['September', 'October', 'November']
	    primavera = ['March', 'April', 'May']
	    estate = ['June', 'July', 'August']
	    if inverno.include?(time.strftime("%B"))
	    	stagionee = 'Inverno'
	    elsif autunno.include?(time.strftime("%B"))
	    	stagionee = 'Autunno'
	    elsif primavera.include?(time.strftime("%B"))
	    	stagionee = 'Primavera'
	    elsif estate.include?(time.strftime("%B"))
	    	stagionee = 'Estate'
	    end
	    self.data = time
	    self.orientamentosp = 0
	    self.calcolo=0
	    self.memoria=0
	    self.richiamo=0
	    self.linguaggio=0
	    self.totale=0
	    if self.giorno == time.day
            	self.orientamentosp +=1
	    end
            if self.mese == time.strftime("%B")
		self.orientamentosp +=1
	    end
            if self.anno == time.year
		self.orientamentosp +=1
            end
	    if self.stagione == stagionee
            	self.orientamentosp +=1
	    end
            if self.citta == self.citta
		self.orientamentosp +=1
	    end
	    if self.regione == self.regione
		self.orientamentosp +=1
	    end
            if self.stato == 'Italia'
		self.orientamentosp +=1
	    end
	    if self.parola1 == 'cane'
		self.memoria +=1
	    end
	    if self.parola2 == 'casa'
		self.memoria +=1
	    end
	    if self.parola3 == 'forchetta'
		self.memoria +=1
	    end
	    if self.somma == 32
		self.calcolo = 5
	    end
            if self.parola4 == 'cane'
		self.richiamo +=1
	    end
	    if self.parola5 == 'casa'
		self.richiamo +=1
	    end
	    if self.parola6 == 'forchetta'
            	self.richiamo +=1
	    end
	    if self.oggetto1 == 'palla'
		self.linguaggio +=1
	    end
	    if self.oggetto2 == 'orologio'
  		self.linguaggio +=1
	    end
	    if self.frase == 2
		self.linguaggio +=1
	    end
	    self.totale = self.orientamentosp + self.memoria + self.calcolo + self.richiamo + self.linguaggio
   end
end

TogetherAnne/app/controllers/monitoraggios_controller.rb
class MonitoraggiosController < ApplicationController

  # GET /monitoraggios
  # GET /monitoraggios.json
 # def index
    #@monitoraggios = Monitoraggio.all
 # end

  # GET /monitoraggios/1
  # GET /monitoraggios/1.json
  def show
	@monitorragios = User.find(params[:user_id])
        @user = User.find(params[:user_id])
  end

  # GET /monitoraggios/new
  def new
    @monitoraggio = Monitoraggio.new
  end

  # GET /monitoraggios/1/edit
  def edit
  end

  # POST /monitoraggios
  # POST /monitoraggios.json
  def create
    #@monitoraggio = Monitoraggio.new(monitoraggio_params)
   
    #@user = current_user
    @monitoraggio = current_user.monitoraggios.build(monitoraggio_params)
        if @monitoraggio.save
            flash[:success] = "I risultati sono stati salvati, per visualizzarli vai su Monitora i tuoi risultati"
            redirect_to root_path
		
	else
            flash[:danger] = "ATTENZIONE! Non è stato possibile crearlo"
            redirect_to root_path
            return
        end

   # respond_to do |format|
     # if @monitoraggio.save
      #  format.html { redirect_to @monitoraggio, notice: 'Monitoraggio was successfully created.' }
       # format.json { render :show, status: :created, location: @monitoraggio }
     # else
     #   format.html { render :new }
      #  format.json { render json: @monitoraggio.errors, status: :unprocessable_entity }
     # end
   # end
  end

  # PATCH/PUT /monitoraggios/1
  # PATCH/PUT /monitoraggios/1.json
  def update
    respond_to do |format|
      if @monitoraggio.update(monitoraggio_params)
        format.html { redirect_to @monitoraggio, notice: 'Monitoraggio was successfully updated.' }
        format.json { render :show, status: :ok, location: @monitoraggio }
      else
        format.html { render :edit }
        format.json { render json: @monitoraggio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monitoraggios/1
  # DELETE /monitoraggios/1.json
  def destroy
    @monitoraggio.destroy
    respond_to do |format|
      format.html { redirect_to monitoraggios_url, notice: 'Monitoraggio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monitoraggio
      @monitoraggio = Monitoraggio.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monitoraggio_params
      params.require(:monitoraggio).permit(:data, :orientamentosp, :memoria, :calcolo, :richiamo, :linguaggio, :totale, :giorno, :mese, :anno, :stagione, :citta, :regione, :stato, :parola1, :parola2, :parola3, :somma, :parola4, :parola5, :parola6, :oggetto1, :oggetto2, :frase, :punteggio)   
    end  
end

TogetherAnne/app/helpers/monitoraggios_helper.rb
module MonitoraggiosHelper
end

TogetherAnne/app/views/monitoraggios/_form.html.erb
<%= form_with(model: monitoraggio, local: true) do |form| %>
  <% if monitoraggio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monitoraggio.errors.count, "error") %> prohibited this monitoraggio from being saved:</h2>

      <ul>
      <% monitoraggio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_select :data, id: :monitoraggio_data %>
  </div>

  <div class="field">
    <%= form.label :orientamentosp %>
    <%= form.number_field :orientamentosp, id: :monitoraggio_orientamentosp %>
  </div>

  <div class="field">
    <%= form.label :memoria %>
    <%= form.number_field :memoria, id: :monitoraggio_memoria %>
  </div>

  <div class="field">
    <%= form.label :calcolo %>
    <%= form.number_field :calcolo, id: :monitoraggio_calcolo %>
  </div>

  <div class="field">
    <%= form.label :richiamo %>
    <%= form.number_field :richiamo, id: :monitoraggio_richiamo %>
  </div>

  <div class="field">
    <%= form.label :linguaggio %>
    <%= form.number_field :linguaggio, id: :monitoraggio_linguaggio %>
  </div>

  <div class="field">
    <%= form.label :totale %>
    <%= form.number_field :totale, id: :monitoraggio_totale %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

TogetherAnne/app/views/monitoraggios/edit.html.erb
<h1>Editing Monitoraggio</h1>

<%= render 'form', monitoraggio: @monitoraggio %>

<%= link_to 'Show', @monitoraggio %> |
<%= link_to 'Back', monitoraggios_path %>

TogetherAnne/app/views/monitoraggios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monitoraggios</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Orientamentosp</th>
      <th>Memoria</th>
      <th>Calcolo</th>
      <th>Richiamo</th>
      <th>Linguaggio</th>
      <th>Totale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monitoraggios.each do |monitoraggio| %>
      <tr>
        <td><%= monitoraggio.data %></td>
        <td><%= monitoraggio.orientamentosp %></td>
        <td><%= monitoraggio.memoria %></td>
        <td><%= monitoraggio.calcolo %></td>
        <td><%= monitoraggio.richiamo %></td>
        <td><%= monitoraggio.linguaggio %></td>
        <td><%= monitoraggio.totale %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

TogetherAnne/app/views/monitoraggios/new.html.erb
<% flash.each do |type, msg| %>
    <div class = "alert alert-info">
       <%= msg %>
    </div>
<% end %>
<div class="col-md-6 col-md-offset-3">

    <div class="center jumbotron">
<h1>Test</h1>
<%= form_for :monitoraggio,  url: user_monitoraggios_path(current_user), html: { method: :post } do |f| %>
      <p>
      <br>
      <h5>Scrivi negli appositi spazi giorno, mese, anno e stagione corrente</h5><br>
      <%= f.label :Giorno %>
      <%= f.text_field :giorno, class: 'form-control', placeholder: "Es: 2" %>
	</p>
        <p>
      <%= f.label :Mese %>
      <%= f.text_field :mese, class: 'form-control', placeholder: "Es: March (scrivi il mese in inglese, se ti trovi in difficoltà fatti aiutare o usa google translate dal web)" %>
	</p>
	<p>
      <%= f.label :Anno %>
      <%= f.text_field :anno, class: 'form-control', placeholder: "Es: 1998" %>
	</p>
	<p>
      <%= f.label :Stagione %>
      <%= f.text_field :stagione, class: 'form-control', placeholder: "Es: Inverno" %>
	</p>
	<p>
	<br>
	<h5>Scrivi le informazioni richieste facendo riferimento al luogo in cui abiti</h5><br>
      <%= f.label :Città %>
      <%= f.text_field :citta, class: 'form-control', placeholder: "Es: Roma" %>
	</p>
	<p>
      <%= f.label :Regione %>
      <%= f.text_field :regione, class: 'form-control', placeholder: "Es: Lombardia" %>
	</p>
	<p>
      <%= f.label :Stato %>
      <%= f.text_field :stato, class: 'form-control', placeholder: "Es: Italia" %>
	</p>
	<p>
	<br>
	<h5>Scrivi le parole, nell'ordine corretto, che hai letto prima di iniziare il test</h5><br>
      <%= f.label :Parola_1%>
      <%= f.text_field :parola1, class: 'form-control', placeholder: "Es: cavallo" %>
      	</p>
	<p>
      <%= f.label :Parola_2%>
      <%= f.text_field :parola2, class: 'form-control' %>
	</p>
	<p>
      <%= f.label :Parola_3%>
      <%= f.text_field :parola3, class: 'form-control' %>
	</p>
	<p>
	<br>
      <%= f.label :Fai_la_somma%>
	<br>
	<h5>12+20</h5>
      <%= f.text_field :somma, class: 'form-control', placeholder: "Es: 21" %>
	</p>
	<p>
	<br>
	<h5>Scrivi nuovamente le parole, nell'ordine corretto, che hai letto prima di iniziare il test, non copiare le risposte precedenti</h5><br>
      <%= f.label :Parola_1%>
      <%= f.text_field :parola4, class: 'form-control' %>
      	</p>
	<p>
      <%= f.label :Parola_2%>
      <%= f.text_field :parola5, class: 'form-control' %>
	</p>
	<p>
      <%= f.label :Parola_3%>
      <%= f.text_field :parola6, class: 'form-control' %>
	</p>
	<p>
	<br>
	<h5>Scrivi nello spazio corretto il nome degli oggetti riportati in figura</h5><br>
      <h4>1</h4><%= image_tag "palla.jpg", :size => "50x70" %><br>
      <h4>2</h4><%= image_tag "orologio1.jpg", :size => "70x70" %>
      </p>
     

        </p>
	<p>
      <%= f.label :Oggetto_1%>
      <%= f.text_field :oggetto1, class: 'form-control' %>
	</p>
	<p>
      <%= f.label :Oggetto_2%>
      <%= f.text_field :oggetto2, class: 'form-control' %>
 	</p>
	<p>
	<br>
	<h5>Scegli il numero della frase corrispondente che contenga almeno soggetto e verbo</h5><br>
	<h5>1)Bel gatto</h5><br>
	<h5>2)Io sono molto felice</h5><br>
	<h5>3)Gatto vivace</h5><br>
      <%= f.label :Frase%>
      <%= f.text_field :frase, class: 'form-control', placeholder: "Indica il numero corrispondente alla frase scelta, es: 1" %>
	</p>
	<p>
	</p>
	
     

      <%= f.submit "Invia", class: "btn btn-primary" %>

<% end %>

</div>
</div>

TogetherAnne/app/views/monitoraggios/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.demenza? %>
	<div class="col-md-6 col-md-offset-3">
	<table class="table table-bordered table-primary">
	  <thead>
	    <tr class="table-primary">
	      <th scope="col">Data</th>
	      <th scope="col">Orientamento s-p</th>
	      <th scope="col">Memoria</th>
	      <th scope="col">Calcolo</th>
	      <th scope="col">Richiamo</th>
	      <th scope="col">Linguaggio</th>
	      <th scope="col">Totale</th>
	    </tr>
	  </thead>

	  <tbody>
	    
		<% @user.monitoraggios.each do |m| %>
			<tr>
			<% m.somma_punteggio %>
	      		<th scope="row"><%= m.data %></th>
			<th><%= m.orientamentosp %>/7</th>
			<th><%= m.memoria %>/3</th>
			<th><%= m.calcolo %>/5</th>
			<th><%= m.richiamo %>/3</th>
			<th><%= m.linguaggio %>/3</th>
			<th><%= m.totale %>/21</th>
			</tr>
	       <% end %>
	    
	   
	  </tbody>
	</table>
<% else %>
	
	<div class="col-md-6 col-md-offset-3">
	<table class="table table-bordered table-primary">
	  <thead>
	    <tr class="table-primary">
	      <th scope="col">Data</th>
	      <th scope="col">Orientamento s-p</th>
	      <th scope="col">Memoria</th>
	      <th scope="col">Calcolo</th>
	      <th scope="col">Richiamo</th>
	      <th scope="col">Linguaggio</th>
	      <th scope="col">Totale</th>
	    </tr>
	  </thead>

	  <tbody>
	    <tr>
		<% if @user.esiste_monitoraggio == true %>
			<% @user.prendi_user_ass.each do |m| %>
				<% m.somma_punteggio %>
		      		<th scope="row"><%= m.data %></th>
				<th><%= m.orientamentosp %>/7</th>
				<th><%= m.memoria %>/3</th>
				<th><%= m.calcolo %>/5</th>
				<th><%= m.richiamo %>/3</th>
				<th><%= m.linguaggio %>/3</th>
				<th><%= m.totale %>/21</th>
		       <% end %>
		<% else %>
			<%= link_to 'Indietro', root_path(current_user), data: {confirm: "Non hai ancora nessun risultato da monitorare, clicca ok per tornare alla tua schermata di home"} %>	
		<% end %>	
	    </tr>
	   
	  </tbody>
	</table>
<% end %>

<h4>Il MMSE (Mini-Mental State Examination) rappresenta un rapido e sensibile strumento per l'esplorazione della funzione cognitiva e delle sue modifiche nel tempo. Fra le versioni disponibili si propone quella si propone quella validata dal gruppo di Ricerca Geriatrica di Brescia, togliendo gli step che non potevano essere valutati tramite la tecnologia utilizzata, quindi il punteggio totale è pari a un massimo di 21.
Un punteggio inferiore a 16 determina la presenza della demenza, il punteggio è direttamente proporzionale all'efficienza delle funzioni cognitive.</h4>





</div>