TogetherAnne/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_scope :user do
    #get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #end
  
	
  #devise_for :users, :controllers => { :callbacks_controller_controller => "controllers/callbacks_controller_controller" }

  root 'static_pages#home'

  get 'static_pages/suggerimenti'

  get 'static_pages/aboutus'
  
  resources :users do
  	resources :monitoraggios
	resources :associaziones
	#get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
	#delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end
  

  #devise_scope :user do
    #get ' /users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    #get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  #end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TogetherAnne/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def suggerimenti
  end

  def aboutus
  end
end

TogetherAnne/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

TogetherAnne/app/views/static_pages/aboutus.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Cosa è TogetherAnne?</h1>
    <p class="lead">Lo scopo dell’applicazione TogetherAnne è quello di aiutare chi soffre della demenza cognitiva, in tutte le sue forme, soprattutto nella fase iniziale, e chi si occupa di loro, a essere consapevoli della propria o altrui condizione e a spronarlo ad allenare la mente e a non chiudersi in se stessi, attraverso suggerimenti sia di carattere medico che non. Che aspetti? Registrati subito!</p>
	 <%= link_to "Registrati", new_user_registration_path, class: "btn btn-lg btn-link" %>
	<%= link_to "Accedi", new_user_session_path, class: "btn btn-lg btn-link" %>
	<%= link_to "Torna alla schermata iniziale", root_path, class: "btn btn-lg btn-link" %>
  </div>
</div>

TogetherAnne/app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="post_form">
        <%= render 'devise/shared/home_d' %>
      </section>
    </aside>

  </div>
<% else %>



<div class="col-md-6 col-md-offset-3">
    <div class="center jumbotron">

        <h1>Benvenuto in TogethereAnne</h1><br>

        <h2>  </h2>
	<div class="col-md-6 col-md-offset-3">
        <%= link_to "Registrati", new_user_registration_path, class: "btn btn-lg btn-primary" %>

        <%= link_to "Accedi", new_user_session_path, class: "btn btn-lg btn-primary" %>
	</div><p><br><br><br>
	<h3>Non vuoi registrarti? Visita la parte dei suggerimenti visibile a tutti</h1><%= link_to "Vai ai suggerimenti", static_pages_suggerimenti_path, class: "btn btn-lg btn-link" %>
        <%= link_to "About us", static_pages_aboutus_path, class: "btn btn-lg btn-link" %></p>
    </div>
	 
	
       
</div>


<% end %>

TogetherAnne/app/views/static_pages/suggerimenti.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="center jumbotron">
<h1>Suggerimenti</h1>
<div class="card text-white bg-primary" >
  
  <div class="card-body">
    <h2 class="card-title">Attività ricreativa</h2>
    <p class="card-text"><h3>Prendi fogli, pennarelli o pennelli e acquarelli e inizia a dipingere! Ciò stimola la creatività e a esprimere se stessi. Se sei in compagnia meglio! Fate una gara in cui chi disegna/dipinge meglio un oggetto scelto di comune accordo, decide che mangiare per cena! Che aspetti, cerca di vincere! .</h3></p>
  </div>
</div>

<div class="card text-white bg-success" >
  
  <div class="card-body">
    <h2 class="card-title">Alimentazione</h2>
    <p class="card-text">Mantenere una dieta varia, alternando carni bianche e rosse, non
dimenticando pesce, formaggi e uova. Assicurarsi che vi sia un
adeguato apporto di fibre e vitamine (uso di frutta e verdura), utili
anche per correggere eventuali problemi di stipsi.</p>
  </div>
</div>
<div class="card text-white bg-danger" >
  
  <div class="card-body">
    <h2 class="card-title">Mobilità</h2>
    <p class="card-text">La mobilità è un aspetto molto importante, passeggiate accompagnati e uscite all'aria aperta. Al vostro ritorno eseguite degli esercizi da seduti compiendo movimenti circolari con gli arti a rotazione, poi distenderli e piegarli. Questa aiuterà anche la circolazione!</p>
  </div>
</div>
<div class="card text-white bg-warning" >
  
  <div class="card-body">
    <h2 class="card-title">Comunicazione</h2>
    <p class="card-text">Parlare è la chiave. Esprimete sempre ciò che provate e le vostre esigenze, non dovete estraniarvi se vi trovate in difficoltà o vi sentite incompresi.</p>
  </div>
</div>
<div class="card text-white bg-info">
  <div class="card-body">
    <h2 class="card-title">Memoria</h2>
    <p class="card-text">Durante una passeggiata scegliete una lettera e guardandovi intorno cercate più oggetti possibili che inizino con quella lettera.</p>
  </div>
</div><br>
 <%= link_to "Indietro", root_path, class: "btn btn-lg btn-light" %>
</div>
</div>