TogetherAnne/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_scope :user do
    #get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #end
  
	
  #devise_for :users, :controllers => { :callbacks_controller_controller => "controllers/callbacks_controller_controller" }

  root 'static_pages#home'

  get 'static_pages/suggerimenti'

  get 'static_pages/aboutus'
  
  resources :users do
  	resources :monitoraggios
	resources :associaziones
	#get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
	#delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end
  

  #devise_scope :user do
    #get ' /users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    #get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  #end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TogetherAnne/app/models/associazione.rb
class Associazione < ApplicationRecord
   belongs_to :user
   validates :user_id, presence: true
  
end

TogetherAnne/app/controllers/associaziones_controller.rb
class AssociazionesController < ApplicationController


  # GET /associaziones
  # GET /associaziones.json
  def index
    #@associaziones = Associazione.all
  end

  # GET /associaziones/1
  # GET /associaziones/1.json
  def show
	@associazione = User.find(params[:user_id]).associazione
        @user = User.find(params[:user_id])
  end

  # GET /associaziones/new
  def new
    @associazione = Associazione.new
  end

  # GET /associaziones/1/edit
  def edit
  end

  # POST /associaziones
  # POST /associaziones.json
  def create
 	#@user = current_user
	
        	@associazione = current_user.build_associazione(associazione_params)

   # @associazione = Associazione.new(associazione_params)
   # @user = current_user
    #@associazione = @user.build(associazione_params)
		
			if @associazione.save
			    con = @associazione.codicea
			    if (User.exists?(@associazione.codicea) != false && (User.exists?(nome: @associazione.nomea)) == true && (User.exists?(cognome: @associazione.cognomea)) == true )
			    	flash[:success] = "L'associazione è riuscita con successo"
			    	redirect_to root_path
			    else
				@associazione.destroy
				flash[:danger] = "ATTENZIONE! i campi inseriti per l'associazione sono errati"
				redirect_to root_path
				return
			    end
			else
			    flash[:danger] = "ATTENZIONE! Non è stato possibile portare a termine l'associazione"
			    redirect_to root_path
			    return
			end

		
		

    #respond_to do |format|
     # if @associazione.save
     #   format.html { redirect_to @associazione, notice: 'Associazione was successfully created.' }
    #    format.json { render :show, status: :created, location: @associazione }
   #   else
    #    format.html { render :new }
    #    format.json { render json: @associazione.errors, status: :unprocessable_entity }
   #   end
  #  end
  end

  # PATCH/PUT /associaziones/1
  # PATCH/PUT /associaziones/1.json
  def update
    respond_to do |format|
      if @associazione.update(associazione_params)
        format.html { redirect_to @associazione, notice: 'Associazione was successfully updated.' }
        format.json { render :show, status: :ok, location: @associazione }
      else
        format.html { render :edit }
        format.json { render json: @associazione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associaziones/1
  # DELETE /associaziones/1.json
  def destroy
    current_user.associazione.destroy
    flash[:success] = "L'associazione è stata cancellata con successo"
    redirect_to root_path
      
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associazione
      @associazione = Associazione.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associazione_params
      params.require(:associazione).permit(:nomea, :cognomea, :codicea)
    end
end

TogetherAnne/app/helpers/associaziones_helper.rb
module AssociazionesHelper
end

TogetherAnne/app/views/associaziones/_form.html.erb
<%= form_with(model: associazione, local: true) do |form| %>
  <% if associazione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(associazione.errors.count, "error") %> prohibited this associazione from being saved:</h2>

      <ul>
      <% associazione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nomea %>
    <%= form.text_field :nomea, id: :associazione_nomea %>
  </div>

  <div class="field">
    <%= form.label :cognomea %>
    <%= form.text_field :cognomea, id: :associazione_cognomea %>
  </div>

  <div class="field">
    <%= form.label :codicea %>
    <%= form.number_field :codicea, id: :associazione_codicea %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

TogetherAnne/app/views/associaziones/edit.html.erb
<h1>Editing Associazione</h1>

<%= render 'form', associazione: @associazione %>

<%= link_to 'Show', @associazione %> |
<%= link_to 'Back', associaziones_path %>

TogetherAnne/app/views/associaziones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Associaziones</h1>

<table>
  <thead>
    <tr>
      <th>Nomea</th>
      <th>Cognomea</th>
      <th>Codicea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
  </tbody>
</table>

<br>

TogetherAnne/app/views/associaziones/new.html.erb
<h1>New Associazione</h1>
<% flash.each do |type, msg| %>
    <div class = "alert alert-info">
       <%= msg %>
    </div>
<% end %>
<div class="col-md-6 col-md-offset-3">
<%= form_for :associazione,  url: user_associaziones_path(current_user), html: { method: :post } do |f| %>
 

      <div class="center jumbotron">
      <h1>Associazione</h1>
      <%= f.label :Nome %>
      <%= f.text_field :nomea, class: 'form-control' %>

      <%= f.label :Cognome %>
      <%= f.text_field :cognomea, class: 'form-control' %>

      <%= f.label :Codice_associazione %>
      <%= f.text_field :codicea, class: 'form-control' %><br>
      <%= f.submit "Associa", class: "btn btn-lg btn-primary" %>
</div>
<% end %>
<%= link_to 'Back', root_path %>

TogetherAnne/app/views/associaziones/show.html.erb
<p id="notice"><%= notice %></p>
<% flash.each do |type, msg| %>
    <div class = "alert alert-info">
       <%= msg %>
    </div>
<% end %>
<div class="col-md-6 col-md-offset-3">
	     <div class="center jumbotron">
      <h1>Associazione</h1>
	<p>
	  <strong>Nomea:</strong>
	  <%= current_user.associazione.nomea %>
	</p>

	<p>
	  <strong>Cognomea:</strong>
	  <%= current_user.associazione.cognomea %>
	</p>

	<p>
	  <strong>Codicea:</strong>
	  <%= current_user.associazione.codicea %>
	</p>


<%= link_to 'Cancella', user_associazione_path(current_user), method: :delete, data: {confirm: "Sei sicuro di voler eliminare l'associazione?"} %>		
<%= link_to 'Back', root_path %>
</div>
</div>